### ISSUE TITLE
POIs nor Entities chunks are trimmed

### ISSUE THREAD

**Issue by ghost** [Puremin0rez/WorldBorder#12]
Hello !
Thank you very much for maintaining this plugin.
However, there is a small problem with the trim feature : It doesn't erase POis data (`poi` folder for 1.14+ worlds) nor entities (`entities` folder for 1.17+ worlds).
If you plan to add this feature, the plugin should scan all three types of files independently, as there may be POI chunks or entities that exist without a corresponding region chunk. For example if you trimmed your world with the current version of the plugin.
Thank you for reading this, and have a nice day !

**Comment by Puremin0rez** [comment]
This has been resolved with the merge of #15
