### ISSUE TITLE
Worldborder randomly shrinking

### ISSUE THREAD

**Issue by cqm3ron** [Puremin0rez/WorldBorder#17]
I set my worldborder size to 12288 x 6144, using command '/wb set 12288 6144' but whenever my server restarts it shrinks to 9999 x 6144. Why is this?

**Comment by Puremin0rez** [comment]
Are you using a Minecraft host? Some hosts have been known to limit the maximum size allowed, and they usually automatically adjust this size on server startup.

I have just checked this on my end and I'm unable to reproduce the issue.

**Comment by cqm3ron** [comment]
I use Shockbyte, is there any way to fix this?

**Comment by Puremin0rez** [comment]
You will need to contact your host and let them know that this is something that is inconveniencing you and see if they're able to resolve this. They are intentionally imposing a limit which is preventing you from making your border larger.
