### ISSUE TITLE
Please update to 1.16.5

### ISSUE THREAD

**Issue by rochadvdgit** [Puremin0rez/WorldBorder#5]
That's it!

**Comment by Puremin0rez** [comment]
The current version should work perfectly fine with 1.16.5.

The only difference between Minecraft 1.16.4 and 1.16.5 was a crash fix.

**Comment by Puremin0rez** [comment]
You can find the latest versions here: https://github.com/Puremin0rez/WorldBorder/releases

The latest release will work perfectly fine on 1.16.5.
