### ISSUE TITLE
Add ability to bypass with permissions

### ISSUE THREAD

**Issue by Prof-Bloodstone** [Puremin0rez/WorldBorder#8]
Currently you can only enable/disable bypass with WB command, which is lacking many features.
It'd be awesome to be able to do it using permissions too.

I imagine than if someone is on bypass list, their permission gets ignored:
https://github.com/Puremin0rez/WorldBorder/blob/master/src/main/java/com/wimbli/WorldBorder/BorderCheckTask.java#L58

Happy to implement and PR at some point, if it'd be accepted :)

**Comment by Puremin0rez** [comment]
Thanks for the feature suggestion! Added in https://github.com/Puremin0rez/WorldBorder/commit/abb9329b1b8379a8d71b49da7ba697081c8f6ac1

I'll be releasing an actual build soon, but you can grab the latest build from [Github Actions](https://github.com/Puremin0rez/WorldBorder/actions) if you need it now.
